redis:
  # Redis 数据库索引（默认为0）
  database: 0
  host: localhost
  port: 6379
  # Redis 服务器密码(默认为空)
  password:
  # 连接池最大连接数（使用负值表示没有限制）
  pool.max-active: 8
  # 连接池中的最大空闲连接
  pool.max-idle: 8
  # 连接池中的最小空闲连接
  pool.min-idle: 0
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  pool.max-wait: -1
  # 设置连接超时
  timeout: 0